### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by amomchilov** [trilemma-dev/SecureXPC#11]
- [ ] `XPCError/remote(_:)` is an unresolved reference.
- [ ] ["regular" XPC service support](https://github.com/trilemma-dev/SecureXPC/pull/10) isn't documented yet
- [ ] Is doesn't look like `<# placeholders #>` work in docc. How did you intend for these to work, @jakaplan?
     <img width="555" alt="image" src="https://user-images.githubusercontent.com/5703449/141035942-57ba4779-798c-460e-9a28-fa6e68201018.png">

**Comment by jakaplan** [comment]
I intended the placeholders to work as shown. The intention was that if someone copies and pastes that into Xcode then it'll result in a placeholder:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/5177359/141050935-43a52a92-0750-4f1e-b819-bd811fe560f2.png">

**Comment by amomchilov** [comment]
Have the three points in the body been resolved? None of them are checked off.

**Comment by jakaplan** [comment]
> Have the three points in the body been resolved? None of them are checked off.

- `XPCError.Remote` no longer exists
- XPC Services are documented, except in the readme.md which needs to be revised before the next release
- <# placeholders #> are implemented as intended
