### ISSUE TITLE
`XPC_ERROR_CONNECTION_INTERRUPTED` doesn't appear to actually behave as documented

### ISSUE THREAD

**Issue by jakaplan** [trilemma-dev/SecureXPC#70]
After releasing 0.3.0 of SecureXPC I started updating [SwiftAuthorizationSample](https://github.com/trilemma-dev/SwiftAuthorizationSample) and have run into an unexpected issue:
1. Over XPC the app asks the helper tool to uninstall itself
2. As part of the helper tool uninstalling itself, the helper tool terminates
3. This results in the client receiving `XPC_ERROR_CONNECTION_INTERRUPTED`.
  i. This is expected, Apple's documentation for interrupted says: "Will be delivered to the connection’s event handler if the remote service exited."
4. Installer the helper tool again (under the hood via `SMJobBless`).
5. The next `send` using the client results in a `XPC_ERROR_CONNECTION_INVALID`
  i. This is **unexpected**, Apple's documentation for interrupted also says: "The connection is still live even in this case, and resending a message will cause the service to be launched on-demand."
 ii. I can confirm the service is **not** launched on-demand.
6. The subsequent `send` using the client results in the service being launched.
 i. This is not because of anything XPC is doing automatically, it's because when we received `XPC_ERROR_CONNECTION_INVALID` in step 4 we perform `self.connection = nil` which means we establish a new connection on the next `send`.

**Comment by jakaplan** [comment]
A simple way we can resolve this is to always set `self.connection = nil` when we receive `XPC_ERROR_CONNECTION_INTERRUPTED`.  @amomchilov thoughts on us doing this? It means we're explicitly going against Apple's documentation, but appears their implementation is bugged. (At least on my version of macOS, which is currently 11.6.2.)

**Comment by amomchilov** [comment]
> i. This is unexpected, Apple's documentation for interrupted also says: "The connection is still live even in this case, and resending a message will cause the service to be launched on-demand."
ii. I can confirm the service is not launched on-demand.

I don't think that's unexpected. They were talking about the process *merely* exiting. Here's it's existing, and deleting itself.

> The subsequent send using the client results in the service being launched.

Now *that's* what I find to be unexpected. How did the service relaunch, if it deleted itself?

**Comment by jakaplan** [comment]
> > The subsequent send using the client results in the service being launched.
> 
> Now _that's_ what I find to be unexpected. How did the service relaunch, if it deleted itself?

Because I'm dumb and wrote the repro steps wrong, missing a key step. Will go revise them now and then leave another comment :)

**Comment by amomchilov** [comment]
Haahaha that makes quite a difference, doesn't it!

May I suggest renaming this issue to:

> `XPC_ERROR_CONNECTION_INTERRUPTED` misbehaves when re-installing a service
