### ISSUE TITLE
[help] How can I use FileHandle as argument of withMessageType

### ISSUE THREAD

**Issue by chaosong** [trilemma-dev/SecureXPC#87]
I searched the code repository, and didn't find any code to handle this situation. Is there a Codable FileHandle example? 

Thanks!

**Comment by jakaplan** [comment]
This is not currently supported. SecureXPC only supports types which can be (de)serialized, which is what `Codable` represents. File handles are inherently live references and therefore can't be serialized.

Note the underlying XPC framework does support sending file handles, but it's not supported by SecureXPC.

**Comment by jakaplan** [comment]
The [0.5.2 release](https://github.com/trilemma-dev/SecureXPC/releases/tag/0.5.2) now supports this via the new `XPCFileDescriptorContainer`.
